### PR TITLE
Making BIND generic

### PR DESCRIPTION
**Pull request by pasgou**
I Propose the base of a modification for the BIND template.

What i don't know how to do : making that the user entrie is correct and acceptable by bind (is it an IP address or "none"?) and making the code is sure to make impossible the user to break down the servers.

### CODE REVIEW

**Comment by YannickB** [comment]
Hi,

It looks ok for me with only two little correction : 
-you should use only lesser case for the name of the option, so "Slave_IP" should be renamed "slave_ip".
-I think allow_transfor is not a required configuration, so if the option isn't filled we should not set this line. Otherwise if the user do not fill the option, the allow_transfer will be empty and may cause an error.

Thank you!

**Comment by pasgou** [comment]
Ok

Could you correct the second point as I don’t know how to.

In the documentation i have read ( http://www.zytrax.com/books/dns/ch6/ <http://www.zytrax.com/books/dns/ch6/> ) , the allow_transfer option can be at « none », or be an IP, or not to be.
what I would like to know, for my knowledge, is why we could not have an option to configure or a DNS master or a DNS for sue-domain delegation.

Cordialement

Pascal GOUHIER

**Comment by pasgou** [comment]
Lesser case corrected.
I dont know how to correct the second part.

**Comment by pasgou** [comment]
New comment for the generic bind container.

In the Clouder concept, all services of the company are driven from Clouder : ERP (Odoo), Blog (Drupal or Wordpress), Supervision (Shrinken), Mail (Postfix) and even DNS (Bind).

But what if we have some services that aren't driven from Clouder? Example : we have Google for Business with our Domain Name, a payroll server on a TSE or other services that can't be managed from Clouder. What could be great is : 
- Or to be able to manage the bind service from clouder without the pre-required Application entry
- Or to be able to manage only part of the zones
But what if the bind service must be a "master".

What are your advice? Or have you a trick?

**Comment by YannickB** [comment]
Hello, 

The bind container is quite basic currently, it only add some basic configuration and add the A record when you create a new base. You are perfectly free to go in the bind container and make some change directly on it.

Regarding Google for Business, I think we should improve the dns template to be able to have a "fake" bind container with in the option the Google for business credentials. If this container is selected in the domain link, it will connect to google api to add the A record instead of adding them in the bind container.

**Comment by pasgou** [comment]
Thank you for your answer.
I will study this way of doing things.

**Pull request merged**
