### PR TITLE
[IMP] Migrate to v10

### PR DESCRIPTION
**Pull request by lasley**
- Increase Odoo version to 10.0 in Travis File

Depends:
- [x] OCA/connector#211

### CODE REVIEW

**Comment by lasley** [comment]
@YannickB - How important is it to keep async activated during incubator? I would like to deactivate it so that we can move up to 10.

Reason being - there are methods existing in the new model API that will make things much more efficient. I'd like to start knocking them out, because they'll be easier to back-port due to broken CI than to forward-port due to having to re-audit.

**Comment by YannickB** [comment]
Now that we moved async out of the core it's completely optional and I don't think we'll use it before long. You can deactivate.

**Comment by lasley** [comment]
Sweet! Admittedly I'm just getting tired of having to click the stupid arrow in the M2O fields. v10 you can click anywhere and it pains me to move five millimeters to the right

**Comment by YannickB** [comment]
Ahah, well we have to move to v10 anyway.

**Comment by lasley** [comment]
Alright this looks to work just by the simple upgrade regexes! I love it when that happens, although we'll probably find some errors here and there just due to lack of test coverage. 

You can do a functional test using [this Runbot](https://09679-145-2cc934.runbot.laslabs.io/web?db=09679-145-2cc934-all).

**Comment by YannickB** [comment]
Great :), ready to merge then ?

**Comment by lasley** [comment]
Yup!

**Pull request merged**
